// src/App.tsx
import "./App.css";
import { createEffect, createMemo, createSignal, untrack } from "solid-js";
import { Card, CardButtons } from "./components/Card";
import type { Answer } from "./components/Card";
import { css } from "solid-styled";
import { getRenderedCardString } from "./utils/render";
import { computeDeckInfo } from "./utils/deckInfo";
import { FilePicker } from "./components/FilePicker";
import {
  ankiCachePromise,
  ankiDataSig,
  cardsSig,
  currentReviewCardSig,
  deckInfoSig,
  initializeReviewQueue,
  mediaFilesSig,
  moveToNextReviewCard,
  reviewQueueSig,
  schedulerEnabledSig,
  schedulerSettingsModalOpenSig,
  selectedCardSig,
  selectedDeckIdSig,
  selectedTemplateSig,
  setBlobSig,
  setDeckInfoSig,
  setSchedulerSettingsModalOpenSig,
  setSelectedCardSig,
  setSelectedDeckIdSig,
  templatesSig,
} from "./stores";
import { SRSVisualization } from "./components/SRSVisualization";
import { SchedulerSettingsModal } from "./components/SchedulerSettings";
import { CommandPalette } from "./components/CommandPalette";
import { FileInfo } from "./components/FileInfo";
import { useCommands } from "./useCommands";
import { isTruthy } from "./utils/assert";

function App() {
  // eslint-disable-next-line no-unused-expressions
  css`
    main {
      display: grid;
      grid-template-columns: 300px 1fr 400px;
      min-height: 100vh;
    }

    :global(hr) {
      margin: 1rem 0;
    }

    .layout-left-column {
      grid-column: 1;
      grid-row: 1;
      position: sticky;
      top: 0;
      height: 100vh;
      overflow-y: auto;
      background: var(--color-surface);
      border-right: 1px solid var(--color-border);
      padding: var(--spacing-4);
      text-align: left;
    }

    .layout-center-column {
      grid-column: 2;
      grid-row: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: var(--spacing-4);
      padding: var(--spacing-8) var(--spacing-4);
    }

    .layout-right-column {
      grid-column: 3;
      grid-row: 1;
      position: sticky;
      top: 0;
      height: 100vh;
      overflow-y: auto;
      background: var(--color-surface);
      border-left: 1px solid var(--color-border);
      padding: var(--spacing-4);
      text-align: left;
    }

    @media (max-width: 1200px) {
      main {
        grid-template-columns: 1fr;
        min-height: auto;
      }

      .layout-left-column,
      .layout-center-column,
      .layout-right-column {
        grid-column: 1;
        position: static;
        height: auto;
        overflow: visible;
        border: none;
      }

      .layout-left-column {
        grid-row: 1;
        border-bottom: 1px solid var(--color-border);
      }
      .layout-center-column {
        grid-row: 2;
        background: transparent;
      }
      .layout-right-column {
        grid-row: 3;
        border-top: 1px solid var(--color-border);
      }
    }

    .dropdowns {
      display: flex;
      gap: 1rem;
      justify-content: center;
    }

    .keyboard-hint {
      text-align: right;
      display: inline-block;
      opacity: 0.5;
      grid-column: 1 / -1;
      margin-top: var(--spacing-4);

      button {
        padding: 0.5rem;
        border-radius: 0.25rem;
      }
    }
  `;

  const [activeSide, setActiveSide] = createSignal<"front" | "back">("front");
  const [reviewStartTime, setReviewStartTime] = createSignal<number>(Date.now());
  const commands = useCommands();

  // Compute deck info from anki data (pure derived state)
  const computedDeckInfo = createMemo(() => {
    const ankiData = ankiDataSig();
    return ankiData ? computeDeckInfo(ankiData) : null;
  });

  // Sync computed deck info to global signal and handle initial deck selection
  createEffect(() => {
    const deckInfo = computedDeckInfo();
    if (deckInfo) {
      // Use untrack to read previous deck info without creating a dependency
      const previousDeckInfo = untrack(() => deckInfoSig());
      setDeckInfoSig(deckInfo);

      // Only set initial selected deck when loading a new deck (not when user selects "All Cards")
      // Check if this is a new deck by comparing the deck name
      const isNewDeck = !previousDeckInfo || previousDeckInfo.name !== deckInfo.name;
      if (isNewDeck && deckInfo.subdecks.length > 0) {
        setSelectedDeckIdSig(deckInfo.subdecks[0]!.id);
      }
    }
  });

  // Initialize review queue when cards are loaded and scheduler is enabled
  // Also track selectedDeckIdSig to ensure re-initialization on deck change
  createEffect(() => {
    const cards = cardsSig();
    const templates = templatesSig();
    const schedulerEnabled = schedulerEnabledSig();
    selectedDeckIdSig(); // Track deck changes explicitly

    if (cards.length > 0 && templates && templates.length > 0 && schedulerEnabled) {
      initializeReviewQueue();
    }
  });

  // Get current card based on mode
  const currentCardData = createMemo(() => {
    if (schedulerEnabledSig()) {
      const reviewCard = currentReviewCardSig();
      if (!reviewCard) return null;

      return {
        cardIndex: reviewCard.cardIndex,
        templateIndex: reviewCard.templateIndex,
        reviewCard,
      };
    }

    return {
      cardIndex: selectedCardSig(),
      templateIndex: selectedTemplateSig(),
      reviewCard: null,
    };
  });

  const renderedCard = createMemo(() => {
    const data = currentCardData();
    if (!data) return null;

    const template = cardsSig()[data.cardIndex]?.templates[data.templateIndex];
    const card = cardsSig()[data.cardIndex];

    if (!template || !card) {
      return null;
    }

    const frontSideHtml = getRenderedCardString({
      templateString: template.qfmt,
      variables: { ...card.values },
      mediaFiles: mediaFilesSig(),
    });

    const backSideHtml = getRenderedCardString({
      templateString: template.afmt,
      // https://docs.ankiweb.net/templates/fields.html#special-fields
      variables: { ...card.values, FrontSide: frontSideHtml },
      mediaFiles: mediaFilesSig(),
    });

    return { frontSideHtml, backSideHtml };
  });

  const updateActiveSide = (side: "front" | "back") => {
    setActiveSide(side);
    const card = renderedCard();
    if (!card) return;

    if (side === "front") {
      const audioFilenames = getAudioFilenames(card.frontSideHtml);
      for (const filename of audioFilenames) {
        new Audio(filename).play();
      }
    } else {
      const frontSideAudioFilenames = new Set(getAudioFilenames(card.frontSideHtml));
      const backSideAudioFilenames = new Set(getAudioFilenames(card.backSideHtml));
      const newAudioFilenames = backSideAudioFilenames.difference(frontSideAudioFilenames);

      for (const filename of newAudioFilenames) {
        new Audio(filename).play();
      }
    }

    function getAudioFilenames(html: string) {
      const allAudioContainers = new DOMParser()
        .parseFromString(html, "text/html")
        .querySelectorAll<HTMLAudioElement>(`div.audio-container[data-autoplay] audio`);

      return [...allAudioContainers].map((audio) => audio.src).filter(isTruthy);
    }
  };

  // Calculate intervals for scheduler mode
  const intervals = createMemo(() => {
    if (!schedulerEnabledSig()) return undefined;

    const reviewCard = currentReviewCardSig();
    const queue = reviewQueueSig();

    if (!reviewCard || !queue) return undefined;

    return queue.getNextIntervals(reviewCard);
  });

  return (
    <>
      <main>
        {/* LEFT COLUMN: File Info */}
        <div class="layout-left-column">{deckInfoSig() && <FileInfo />}</div>

        {/* CENTER COLUMN: Card */}
        <div class="layout-center-column">
          {(() => {
            const card = renderedCard();
            if (!card) {
              return cardsSig().length === 0 ? (
                <FilePicker
                  onFileChange={async (file) => {
                    const cache = await ankiCachePromise;
                    await cache.put("anki-deck", new Response(file));

                    setBlobSig(file);
                  }}
                />
              ) : null;
            }

            return (
              <>
                <Card
                  front={<div innerHTML={card.frontSideHtml} />}
                  back={<div innerHTML={card.backSideHtml} />}
                  activeSide={activeSide()}
                  intervals={intervals()}
                  onReveal={() => {
                    updateActiveSide("back");
                    setReviewStartTime(Date.now());
                  }}
                  onChooseAnswer={async (answer: Answer) => {
                    if (schedulerEnabledSig()) {
                      // Scheduler mode: process review
                      const reviewCard = currentReviewCardSig();
                      const queue = reviewQueueSig();

                      if (reviewCard && queue) {
                        const reviewTimeMs = Date.now() - reviewStartTime();
                        await queue.processReview(reviewCard, answer, reviewTimeMs);
                        moveToNextReviewCard();
                      }
                    } else {
                      // Simple mode: just move to next card
                      setSelectedCardSig((prevCard) => prevCard + 1);
                    }

                    updateActiveSide("front");
                    setReviewStartTime(Date.now());
                  }}
                />
                <CardButtons
                  activeSide={activeSide()}
                  intervals={intervals()}
                  onReveal={() => {
                    updateActiveSide("back");
                    setReviewStartTime(Date.now());
                  }}
                  onChooseAnswer={async (answer: Answer) => {
                    if (schedulerEnabledSig()) {
                      // Scheduler mode: process review
                      const reviewCard = currentReviewCardSig();
                      const queue = reviewQueueSig();

                      if (reviewCard && queue) {
                        const reviewTimeMs = Date.now() - reviewStartTime();
                        await queue.processReview(reviewCard, answer, reviewTimeMs);
                        moveToNextReviewCard();
                      }
                    } else {
                      // Simple mode: just move to next card
                      setSelectedCardSig((prevCard) => prevCard + 1);
                    }

                    updateActiveSide("front");
                    setReviewStartTime(Date.now());
                  }}
                />
              </>
            );
          })()}
        </div>

        {/* RIGHT COLUMN: SRS Visualization */}
        <div class="layout-right-column">{cardsSig().length > 0 && <SRSVisualization />}</div>
      </main>

      <SchedulerSettingsModal
        isOpen={schedulerSettingsModalOpenSig()}
        onClose={() => setSchedulerSettingsModalOpenSig(false)}
      />
      <CommandPalette commands={commands()} />
    </>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import "./App.css";
import { computed, ref, watch } from "vue";
import FlashCard from "./components/FlashCard.vue";
import CardButtons from "./components/CardButtons.vue";
import type { Answer } from "./scheduler/types";
import { getRenderedCardString } from "./utils/render";
import { computeDeckInfo } from "./utils/deckInfo";
import {
  activeViewSig,
  ankiDataSig,
  cardsSig,
  currentReviewCardSig,
  deckInfoSig,
  initializeReviewQueue,
  mediaFilesSig,
  moveToNextCard,
  moveToNextReviewCard,
  reviewModeSig,
  reviewQueueSig,
  schedulerEnabledSig,
  schedulerSettingsModalOpenSig,
  selectedCardSig,
  selectedDeckIdSig,
  selectedTemplateSig,
  templatesSig,
  updateDueCardsAfterReview,
} from "./stores";
import StatusBar from "./components/StatusBar.vue";
import FileLibrary from "./components/FileLibrary.vue";
import DeckCreator from "./components/DeckCreator.vue";

import CardBrowser from "./components/CardBrowser.vue";
import SyncPanel from "./components/SyncPanel.vue";
import SchedulerSettings from "./components/SchedulerSettings.vue";
import CommandPalette from "./components/CommandPalette.vue";
import { useCommands } from "./composables/useCommands";
import { getAutoplayAudioSources, playAudio } from "./utils/sound";
import { Info } from "lucide-vue-next";
import Modal from "./design-system/components/primitives/Modal.vue";
import Tooltip from "./design-system/components/primitives/Tooltip.vue";
import { markDataChanged, startAutoSync } from "./lib/autoSync";

const activeSide = ref<"front" | "back">("front");
const reviewStartTime = ref<number>(Date.now());
const commands = useCommands();

// Start background auto-sync timer
startAutoSync();

// Compute deck info from anki data
const computedDeckInfo = computed(() => {
  const ankiData = ankiDataSig.value;
  return ankiData ? computeDeckInfo(ankiData) : null;
});

// Sync computed deck info to global signal and handle initial deck selection
watch(computedDeckInfo, (newDeckInfo, oldDeckInfo) => {
  if (newDeckInfo) {
    deckInfoSig.value = newDeckInfo;

    // Only set initial selected deck when loading a new deck
    const isNewDeck = !oldDeckInfo || oldDeckInfo.name !== newDeckInfo.name;
    if (isNewDeck && newDeckInfo.subdecks.length > 0) {
      selectedDeckIdSig.value = newDeckInfo.subdecks[0]!.id;
    }
  }
});

const selectedSubdeck = computed(() => {
  const info = deckInfoSig.value;
  const id = selectedDeckIdSig.value;
  if (!info || !id) return null;
  return info.subdecks.find((d) => d.id === id) ?? null;
});

const selectedDeckName = computed(() => {
  return selectedSubdeck.value?.name ?? deckInfoSig.value?.name ?? null;
});

const selectedDeckDescription = computed(() => {
  return selectedSubdeck.value?.description || null;
});

const deckInfoModalOpen = ref(false);

// Initialize review queue when cards are loaded (scheduler enabled state is per-deck, checked inside)
watch([cardsSig, templatesSig, selectedDeckIdSig], ([cards, templates]) => {
  if (cards.length > 0 && templates && templates.length > 0) {
    initializeReviewQueue();
  }
});

// Get current card based on mode
const currentCardData = computed(() => {
  if (schedulerEnabledSig.value) {
    const reviewCard = currentReviewCardSig.value;
    if (!reviewCard) return null;

    return {
      cardIndex: reviewCard.cardIndex,
      templateIndex: reviewCard.templateIndex,
      reviewCard,
    };
  }

  return {
    cardIndex: selectedCardSig.value,
    templateIndex: selectedTemplateSig.value,
    reviewCard: null,
  };
});

const renderedCard = computed(() => {
  const data = currentCardData.value;
  if (!data) return null;

  const template = cardsSig.value[data.cardIndex]?.templates[data.templateIndex];
  const card = cardsSig.value[data.cardIndex];

  if (!template || !card) return null;

  const frontSideHtml = getRenderedCardString({
    templateString: template.qfmt,
    variables: { ...card.values },
    mediaFiles: mediaFilesSig.value,
  });

  const backSideHtml = getRenderedCardString({
    templateString: template.afmt,
    variables: { ...card.values, FrontSide: frontSideHtml },
    mediaFiles: mediaFilesSig.value,
  });

  return { frontSideHtml, backSideHtml, cardCss: card.css ?? "" };
});

// Autoplay front-side audio when entering studying mode or when the card changes
watch(
  () => [reviewModeSig.value, renderedCard.value] as const,
  ([mode, card], [oldMode]) => {
    if (mode !== "studying" || !card) return;
    if (oldMode !== "studying" || activeSide.value === "front") {
      activeSide.value = "front";
      for (const filename of getAutoplayAudioSources(card.frontSideHtml)) {
        playAudio(filename);
      }
    }
  },
);

function updateActiveSide(side: "front" | "back") {
  activeSide.value = side;
  const card = renderedCard.value;
  if (!card) return;

  if (side === "front") {
    for (const filename of getAutoplayAudioSources(card.frontSideHtml)) {
      playAudio(filename);
    }
  } else {
    const frontSideAudioFilenames = new Set(getAutoplayAudioSources(card.frontSideHtml));
    const backSideAudioFilenames = new Set(getAutoplayAudioSources(card.backSideHtml));
    const newAudioFilenames = backSideAudioFilenames.difference(frontSideAudioFilenames);
    for (const filename of newAudioFilenames) {
      playAudio(filename);
    }
  }
}

// Calculate intervals for scheduler mode
const intervals = computed(() => {
  if (!schedulerEnabledSig.value) return undefined;

  const reviewCard = currentReviewCardSig.value;
  const queue = reviewQueueSig.value;

  if (!reviewCard || !queue) return undefined;

  return queue.getNextIntervals(reviewCard);
});

function handleAudioButtonClick(src: string) {
  playAudio(src);
}

function handleReveal() {
  updateActiveSide("back");
  reviewStartTime.value = Date.now();
}

async function handleChooseAnswer(answer: Answer) {
  if (schedulerEnabledSig.value) {
    const reviewCard = currentReviewCardSig.value;
    const queue = reviewQueueSig.value;

    if (reviewCard && queue) {
      const reviewTimeMs = Date.now() - reviewStartTime.value;
      const updatedState = await queue.processReview(reviewCard, answer, reviewTimeMs);
      updateDueCardsAfterReview(reviewCard.cardId, updatedState);
      moveToNextReviewCard();
      markDataChanged();
    }
  } else {
    moveToNextCard();
  }

  updateActiveSide("front");
  reviewStartTime.value = Date.now();
}
</script>

<template>
  <StatusBar />

  <!-- BROWSE VIEW -->
  <CardBrowser v-if="activeViewSig === 'browse'" />

  <!-- CREATE DECK VIEW -->
  <DeckCreator v-else-if="activeViewSig === 'create'" />

  <!-- SYNC VIEW -->
  <SyncPanel v-else-if="activeViewSig === 'sync'" />

  <!-- REVIEW VIEW: deck list or studying -->
  <FileLibrary v-else-if="reviewModeSig === 'deck-list'" />

  <main v-else>
    <div class="layout-center-column">
      <template v-if="renderedCard">
        <div v-if="selectedDeckName" class="deck-header">
          <Tooltip :text="selectedDeckDescription ?? 'No description'">
            <button class="deck-info-btn" @click="deckInfoModalOpen = true">
              <Info :size="16" />
            </button>
          </Tooltip>
          <span>{{ selectedDeckName }}</span>
        </div>
        <FlashCard
          :active-side="activeSide"
          :front-html="renderedCard.frontSideHtml"
          :back-html="renderedCard.backSideHtml"
          :card-css="renderedCard.cardCss"
          :intervals="intervals"
          @reveal="handleReveal"
          @choose-answer="handleChooseAnswer"
          @audio-button-click="handleAudioButtonClick"
        />
        <CardButtons
          :active-side="activeSide"
          :intervals="intervals"
          @reveal="handleReveal"
          @choose-answer="handleChooseAnswer"
        />
      </template>
      <p v-else-if="cardsSig.length === 0" class="no-deck-message">
        No deck loaded. Click the
        <button class="link-btn" @click="reviewModeSig = 'deck-list'">Review</button> tab to choose
        a deck.
      </p>
    </div>
  </main>

  <SchedulerSettings
    :is-open="schedulerSettingsModalOpenSig"
    @close="schedulerSettingsModalOpenSig = false"
  />

  <Modal :is-open="deckInfoModalOpen" title="Deck Info" size="sm" @close="deckInfoModalOpen = false">
    <div v-if="selectedSubdeck" class="deck-info-content">
      <dl class="deck-info-dl">
        <dt>Name</dt>
        <dd>{{ selectedSubdeck.fullName }}</dd>
        <dt>Description</dt>
        <dd>{{ selectedSubdeck.description || 'No description' }}</dd>
        <dt>Cards</dt>
        <dd>{{ selectedSubdeck.cardCount }}</dd>
        <dt>New</dt>
        <dd>{{ selectedSubdeck.newCount }}</dd>
        <dt>Learning</dt>
        <dd>{{ selectedSubdeck.learnCount }}</dd>
        <dt>Due</dt>
        <dd>{{ selectedSubdeck.dueCount }}</dd>
      </dl>
    </div>
  </Modal>

  <CommandPalette :commands="commands" />
</template>

<style scoped>
main {
  min-height: calc(100vh - 44px);
}

.layout-center-column {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--spacing-4);
  padding: var(--spacing-8) var(--spacing-4);
}

.deck-header {
  display: flex;
  align-items: center;
  gap: var(--spacing-1-5);
  color: var(--color-text-secondary);
  font-size: var(--font-size-sm);
}

.no-deck-message {
  color: var(--color-text-secondary);
  font-size: var(--font-size-base);
}

.deck-info-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 2px;
  color: var(--color-text-tertiary);
  background: none;
  border: none;
  border-radius: var(--radius-sm);
  cursor: pointer;
  transition: var(--transition-colors);
  box-shadow: none;
}

.deck-info-btn:hover {
  color: var(--color-text-primary);
  background: var(--color-surface-hover);
}

.deck-info-content {
  padding: var(--spacing-2) 0;
}

.deck-info-dl {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: var(--spacing-1-5) var(--spacing-4);
  margin: 0;
  font-size: var(--font-size-sm);
}

.deck-info-dl dt {
  color: var(--color-text-secondary);
  font-weight: var(--font-weight-medium);
}

.deck-info-dl dd {
  margin: 0;
  color: var(--color-text-primary);
}

.link-btn {
  display: inline;
  padding: 0;
  font: inherit;
  color: var(--color-primary);
  background: none;
  border: none;
  box-shadow: none;
  cursor: pointer;
  text-decoration: underline;
}
</style>
